resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml
  - service.yaml

patches:
  - path: ingress_patch.properties.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: record-api-ingress
  - path: hpa_patch.properties.yaml
    target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: record-api-hpa