apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: record-api-autoscaler
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: record-api-deployment
  metrics:
#   Scale app instances (up to 3) when average CPU usage across all pods is 70%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
