# name suffix and commonLabels to be provided imperatively during deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service.yaml
- ingress.properties.yaml

patchesStrategicMerge:
- deployment_patch.properties.yaml
