apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-deployment
spec:
# selector.matchLabels provided via Kustomize
  template:
    spec:
      containers:
        - name: search-api
          image: europeana/search-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /info
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /info
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              # matches volume mount path for json file
              value: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/google_cloud_credentials.json"
          volumeMounts:
            - name: config
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/europeana.user.properties"
              readOnly: true
              subPath: europeana.user.properties
            - name: secret
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/google_cloud_credentials.json"
              subPath: google_cloud_credentials.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: search-api-config-map
        - name: secret
          secret:
            secretName: search-api-secret