apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-deployment
spec:
# selector.matchLabels provided via Kustomize
  template:
    spec:
      containers:
        - name: search-api
          image: europeana/search-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /info
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /info
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 4
          volumeMounts:
            - name: secret-props
              mountPath: "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/europeana.user.properties"
              readOnly: true
              subPath: europeana.user.properties
      volumes:
        - name: secret-props
          secret:
            secretName: search-api-secret-props