resources:
  - deployment.yaml

commonLabels:
  app: search-api

# expects files to be in the same directory
secretGenerator:
  - name: search-api-secret-props
    files:
      - europeana.user.properties
