apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: search-api

# expects files to be in the same directory
secretGenerator:
  - name: search-api-secret-props
    files:
      - europeana.user.properties
